version: "3.9"

services:

  db:
    image: postgres:14.1
    container_name: postgres_cafe
    ports:
      - 5438:5432
    environment:
      - POSTGRES_DB=cafe_menu
      - POSTGRES_USER=mahdi
      - POSTGRES_PASSWORD=123456789
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container_cafe
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 'pg_pass'
    ports:
      - "6060:80"




volumes:
    postgres-data:
    
